trigger:
  - main

pool:
  name: Teste
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        
        steps:
          - task: NodeTool@0
            inputs:
              version: '18.x'
            displayName: 'Install Node.js'
          
          - script: |
              echo 'MONGODB_TEST_URL=$(MONGODB_TEST_URL)' >> .env
              npm install
            displayName: 'npm install'

          - script: |
              npm run build --if-present
            displayName: 'npm build'

          - script: |
              npm run test:unit --if-present
            displayName: 'unit test'

          - script: |
              npm run test:integration --if-present
            displayName: 'integration test'

          - script: |
              npm run test:e2e --if-present
            displayName: 'e2e test'
