trigger:
  - main

pool:
  name: Teste
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          
          - script: |
              echo 'MONGODB_TEST_URL=$(MONGODB_TEST_URL)' >> .env
              npm install
              npm run build --if-present
            displayName: 'npm install and build'

          - script: |
              ls -la
              ls -la build
            displayName: 'List files and build directory'
          
          - script: |
              npm run test:unit
            displayName: 'Unit tests'

          - script: |
              npm run test:integration
            displayName: 'Integration tests'
            
          - script: |
              npm run test:e2e
            displayName: 'E2E tests'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: ./reports/unit
              artifact: unit-tests
              publishLocation: pipeline

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: ./reports/integration
              artifact: integration-tests
              publishLocation: pipeline

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: ./reports/e2e
              artifact: e2e-tests
              publishLocation: pipeline
