trigger:
  - main

variables:
  vmImageName: 'ubuntu-latest'

pool:
  name: Teste

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: Teste
        
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'
          
          - script: |
              echo 'MONGODB_URL=$(MONGODB_URL)' >> .env
              npm install
              npm run build --if-present
              npm run test --if-present
              npm run test:e2e --if-present
            displayName: 'npm install, build and test'
